### ISSUE TITLE
getting backend error

### ISSUE THREAD

**Issue by SanjaySRocks** [riskeco/Samsung-FRP-Bypass#3]
Terminal Logs

```
(env) PS C:\SamsungFRP Unlock> python .\main.py
Traceback (most recent call last):
  File "C:\SamsungFRP Unlock\main.py", line 12, in <module>
    main()
  File "C:\SamsungFRP Unlock\main.py", line 6, in main
    samsungGalaxyToModemMode()
  File "C:\SamsungFRP Unlock\usbswitcher.py", line 20, in samsungGalaxyToModemMode
    dev = usb.core.find(idVendor=SAMSUNG_GALAXY_ID_VENDOR, idProduct=SAMSUNG_GALAXY_ID_PRODUCT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SamsungFRP Unlock\env\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

```

**Comment by longlostnick** [comment]
I installed the latest version of pyusb by pointing my requirements.txt at the latest version on their GH repo:

```
pyusb @ git+https://github.com/pyusb/pyusb@master
```

That being said, I still am not able to get the whole thing working. Running into issues with ADB. I'm not familiar with ADB at all, but seems to get part of the way through and just hangs:

<img width="777" alt="Screenshot 2024-05-31 at 9 06 13 PM" src="https://github.com/riskeco/Samsung-FRP-Bypass/assets/616525/d5c8ac5c-4e1b-4238-8658-9c73982cac7c">

**Comment by SatinSnow** [comment]
I also needed to install the latest version of pyusb along with the devel filter libusb-win32-devel-filter-1.2.6.0.exe to get things going. Now I am stuck with ADB issues as well. If I gain anymore progress I will report back at the bottom of this comment as "EDIT"s. Here is what I currently got so far
No samsung device detected over USB
####### Available serial ports #######
COM3 - USB Serial Device (COM3)
####### End of available serial ports #######
Choose a serial port (default=COM3) :COM3
Initial...
Sending b'AT+KSTRINGB=0,3\r\n'
Received b''
Go to emergency dialer and enter *#0*#, press enter when done

Enabling USB Debugging...
Trying method 0
Sending b'AT+DUMPCTRL=1,0\r\n'
Received b'AT+KSTRINGB=0,3\r\n\r\n+CME ERROR: 100\r\n'
Trying method 1
Sending b'AT+DEBUGLVC=0,5\r\n'
Received b'\r\n+CME Error:PACM(AP),PROTECTED_NO_TOK\r\n\r\nOK\r\n'
Trying method 2
Sending b'AT+SWATD=0\r\n'
Received b'[DR]: CHANGE TO DDEXEAT+SWATD=0\r\n[ATD]: CHANGE TO DDEXE'
Trying method 3
Sending b'AT+ACTIVATE=0,0,0\r\n'
Received b'\r\n+USB  READY\r\n'
Trying method 4
Sending b'AT+SWATD=1\r\n'
Received b'[DR]: CHANGE TO ATDAT+SWATD=1\r\n[ATD]: CHANGE TO ATDBOOTING COMPLETED\r\nBOOTING COMPLETED\r\n'
Trying method 5
Sending b'AT+DEBUGLVC=0,5\r\n'
Received b'AT+DEBUGLVC=0,5\r\n\r\n+CME Error:PACM(AP),PROTECTED_NO_TOK\r\n\r\nOK\r\n'
USB Debugging should be enabled
If USB Debugging prompt does not appear, try unplug/replug the USB cable
Waiting for device with adb
'adb' is not recognized as an internal or external command,
operable program or batch file.
'adb' is not recognized as an internal or external command,
operable program or batch file.
Pushing FRP bypasser binary
'adb' is not recognized as an internal or external command,
operable program or batch file.
Giving it 777 permissions
'adb' is not recognized as an internal or external command,
operable program or batch file.
Executing the binary
'adb' is not recognized as an internal or external command,
operable program or batch file.

EDIT:
I had to install adb / platform tools from the official andoid website and then add it to my path. Now I am stuck where @longlostnick is though I am don't get a "connection refused". I don't believe this changes anything though since it seems to try again and his post shows the daemon was successful. So far my theory is that the daemon doesn't seem to be doing anything because our devices are not being found OR we just can't see what the daemon is doing so we don't quite know how to move forward or interact with it.

**Comment by SatinSnow** [comment]
> I installed the latest version of pyusb by pointing my requirements.txt at the latest version on their GH repo:
> 
> ```
> pyusb @ git+https://github.com/pyusb/pyusb@master
> ```
> 
> That being said, I still am not able to get the whole thing working. Running into issues with ADB. I'm not familiar with ADB at all, but seems to get part of the way through and just hangs:
> 
> <img alt="Screenshot 2024-05-31 at 9 06 13 PM" width="777" src="https://private-user-images.githubusercontent.com/616525/335771674-d5c8ac5c-4e1b-4238-8658-9c73982cac7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDkxMTMsIm5iZiI6MTcxODUwODgxMywicGF0aCI6Ii82MTY1MjUvMzM1NzcxNjc0LWQ1YzhhYzVjLTRlMWItNDIzOC04NjU4LTljNzM5ODJjYWM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwMzMzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzM2ZTdkNmY3N2UwMGM1MDc5ZTgyNmNmNWNjOWUxMGVmODdjNWZjZTgzMzE4YjFmNmUxNDFjNmJkZmE3YzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V4Ie4jp6mNy5c0fWMLtIyS20SLuf3gVbwkNeSjfdP50">

@longlostnick Have you had any further progress yet?

**Comment by bksmartphone** [comment]
Informational post but i will use Bksmartphone For frp [Bypass Google Account](https://bksmartphone.net/) on all devices.

**Comment by SatinSnow** [comment]
> Informational post but i will use Bksmartphone For frp [Bypass Google Account](https://bksmartphone.net/) on all devices.

Thank you. Should I just keep up with whatever you post there?

**Comment by bksmartphone** [comment]
> > Informational post but i will use Bksmartphone For frp [Bypass Google Account](https://bksmartphone.net/) on all devices.
> 
> Thank you. Should I just keep up with whatever you post there?

Yes This is best website for bypass your google account
